apiVersion: apps/v1
kind: Deployment

metadata:
  name: docuhelper-nextjs-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: docuhelper-nextjs
  template:
    metadata:
      labels:
        app: docuhelper-nextjs
    spec:
      containers:
        - name: docuhelper-api-container
          image: docker.bmserver.org/docuhelper-nextjs:$IMAGE_TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: docuhelper-configmap-prod
---

apiVersion: v1
kind: Service

metadata:
  name: docuhelper-nextjs-service

spec:
  type: NodePort
  selector:
    app: docuhelper-nextjs
  ports:
    - protocol: TCP
      targetPort: 3000    # pod 포트
      port: 3000          # 서비스 내부 포트
      nodePort: 30003      # 서비스 외부 포트
