import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import WarpLayer from '@/components/config/WarpLayer';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body
				className={`flex min-h-screen flex-col items-center justify-center ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<WarpLayer>{children}</WarpLayer>
			</body>
		</html>
	);
}
