import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {ApolloProvider} from "@apollo/client";
import {client} from "@/components/config/MyApolloClient";
import WarpLayer from "@/components/config/WarpLayer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <WarpLayer>
            <body
                className={`flex flex-col min-h-screen justify-center items-center ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            {children}
            </body>
        </WarpLayer>
        </html>
    );
}
